/**
 * omp web palette bundled into standalone exports and the share viewer.
 *
 * Brand hue is Mozn's teal ladder — `#04AEAE` → `#03E7E7` → `#01FFFF`, with
 * `#66F0F0` — over midnight-navy surfaces. The brand carries no second accent,
 * so the former violet/plum tiers (syntax keyword/number/type, callout labels,
 * thinking levels, status-line odds and ends) reuse that ladder; values shared
 * by both schemes stay on the dual-background-safe deep teal.
 */
export type WebExportScheme = "dark" | "light";

const COMMON_EXPORT_PALETTE = {
	"--font-mono": 'ui-monospace, "SF Mono", "JetBrains Mono", "Cascadia Mono", Menlo, Consolas, monospace',
	"--body-bg": "var(--bg)",
	"--container-bg": "var(--bg-raised)",
	"--info-bg": "var(--bg-inset)",
	"--text": "var(--fg)",
	"--muted": "var(--fg-muted)",
	"--dim": "var(--fg-faint)",
	"--thinkingText": "var(--fg-muted)",
	"--borderMuted": "color-mix(in srgb, var(--border) 67%, transparent)",
	"--borderAccent": "#168b9a",
	"--selectedBg": "var(--accent-muted)",
	"--success": "var(--ok)",
	"--error": "var(--err)",
	"--warning": "var(--warn)",
	"--userMessageBg": "var(--accent-muted)",
	"--userMessageText": "var(--fg)",
	"--customMessageBg": "var(--bg-overlay)",
	"--customMessageText": "var(--fg-muted)",
	"--customMessageLabel": "#168b9a",
	"--toolPendingBg": "var(--bg-raised)",
	"--toolSuccessBg": "var(--bg-inset)",
	"--toolErrorBg": "color-mix(in srgb, var(--err) 14%, transparent)",
	"--toolTitle": "var(--fg)",
	"--toolOutput": "var(--fg-muted)",
	"--mdHeading": "var(--accent)",
	"--mdLink": "var(--link)",
	"--mdLinkUrl": "var(--fg-faint)",
	"--mdCode": "var(--fg)",
	"--mdCodeBlock": "var(--fg)",
	"--mdCodeBlockBorder": "var(--border)",
	"--mdQuote": "var(--fg-muted)",
	"--mdQuoteBorder": "var(--border-strong)",
	"--mdHr": "var(--border)",
	"--mdListBullet": "var(--accent)",
	"--toolDiffAdded": "var(--ok)",
	"--toolDiffRemoved": "var(--err)",
	"--toolDiffContext": "var(--fg-faint)",
	"--syntaxOperator": "var(--fg)",
	"--syntaxPunctuation": "var(--fg-muted)",
	"--thinkingOff": "var(--fg-faint)",
	"--thinkingMinimal": "var(--fg-faint)",
	"--thinkingLow": "#168b9a",
	"--thinkingMedium": "#04aeae",
	"--thinkingHigh": "var(--accent)",
	"--thinkingXhigh": "var(--warn)",
	"--bashMode": "#168b9a",
	"--pythonMode": "var(--warn)",
	"--statusLineBg": "var(--bg)",
	"--statusLineSep": "var(--fg-faint)",
	"--statusLineModel": "var(--accent)",
	"--statusLinePath": "#168b9a",
	"--statusLineGitClean": "var(--ok)",
	"--statusLineGitDirty": "var(--warn)",
	"--statusLineContext": "var(--fg-muted)",
	"--statusLineSpend": "#168b9a",
	"--statusLineStaged": "var(--ok)",
	"--statusLineDirty": "var(--warn)",
	"--statusLineUntracked": "#168b9a",
	"--statusLineOutput": "#04aeae",
	"--statusLineCost": "#04aeae",
	"--statusLineSubagents": "var(--accent)",
} as const satisfies Record<string, string>;

export const WEB_EXPORT_PALETTES = {
	dark: {
		"--bg": "#080b17",
		"--bg-raised": "#14142b",
		"--bg-inset": "#070c19",
		"--bg-overlay": "#1f222d",
		"--fg": "#f0f5f5",
		"--fg-muted": "#b1bcc3",
		"--fg-faint": "#758696",
		"--accent": "#03e7e7",
		"--accent-muted": "oklch(0.84 0.143 194.8 / 18%)",
		"--ok": "#68ca80",
		"--err": "#f05653",
		"--warn": "#e4b33f",
		"--border": "oklch(1 0 0 / 9%)",
		"--border-strong": "oklch(1 0 0 / 13%)",
		"--ring": "oklch(0.84 0.143 194.8 / 70%)",
		"--link": "#5ad8e5",
		"--syntaxComment": "#758696",
		"--syntaxKeyword": "#03e7e7",
		"--syntaxFunction": "#e4b33f",
		"--syntaxVariable": "#5ad8e5",
		"--syntaxString": "#68ca80",
		"--syntaxNumber": "#01ffff",
		"--syntaxType": "#66f0f0",
	},
	light: {
		"--bg": "oklch(0.985 0.004 195)",
		"--bg-raised": "oklch(1 0 0)",
		"--bg-inset": "oklch(0.95 0.006 195)",
		"--bg-overlay": "oklch(0.965 0.006 195)",
		"--fg": "oklch(0.26 0.03 195)",
		"--fg-muted": "oklch(0.46 0.03 195)",
		"--fg-faint": "oklch(0.58 0.025 195)",
		"--accent": "#04aeae",
		"--accent-muted": "oklch(0.68 0.116 194.8 / 14%)",
		"--ok": "oklch(0.55 0.13 150)",
		"--err": "oklch(0.55 0.19 25)",
		"--warn": "oklch(0.6 0.13 85)",
		"--border": "oklch(0 0 0 / 10%)",
		"--border-strong": "oklch(0 0 0 / 15%)",
		"--ring": "oklch(0.68 0.116 194.8 / 70%)",
		"--link": "#168b9a",
		"--syntaxComment": "#758696",
		"--syntaxKeyword": "oklch(0.40 0.09 194.8)",
		"--syntaxFunction": "#8a6000",
		"--syntaxVariable": "#087f8c",
		"--syntaxString": "#247a3d",
		"--syntaxNumber": "oklch(0.50 0.10 194.8)",
		"--syntaxType": "oklch(0.46 0.09 194.8)",
	},
} as const satisfies Record<WebExportScheme, Record<string, string>>;

/** Serialize one web color scheme as CSS custom-property declarations. */
export function webExportThemeVars(scheme: WebExportScheme): string {
	return Object.entries({ ...COMMON_EXPORT_PALETTE, ...WEB_EXPORT_PALETTES[scheme] })
		.map(([key, value]) => `${key}: ${value};`)
		.join(" ");
}
